# Generated by Django 2.2.7 on 2019-11-14 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor desejado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montante aprovado'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='cpf',
            field=models.CharField(default='', max_length=200, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Renda mensal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='refused_policy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='terms',
            field=models.IntegerField(default=1, verbose_name='Quantidade de parcelas desejadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(default='processing', max_length=200),
        ),
    ]
