# Generated by Django 2.2.7 on 2019-11-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191114_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='approved_terms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de parcelas aprovadas'),
        ),
    ]
